require("config.lazy")
require("config.options")
require("config.keymaps")
require("config.autocmds")

require("plugins.github-copilot")
require("plugins.lspsaga")
require("plugins.nvim-cmp")
require("plugins.nvim-lspconfig")
require("plugins.toggleterm")
require("plugins.tree-sitter")
require("plugins.winresizer")
